services:
  - type: web
    name: retirement-calculator
    env: python
    pythonVersion: 3.12.3 
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
